alias attacks='tail -f -n 2000 /var/log/auth.log'
alias attackcount='cat /var/log/auth.log | wc'
alias autoremove='apt-get autoremove'
alias ban='iptables -I INPUT_CHAIN -j DROP -s'
alias clean='apt-get clean;apt-get autoclean'
alias fix='apt-get -f install'
alias ins='apt-get install $1'
## shortcut for iptables and pass it via sudo# 
alias ipt='sudo /sbin/iptables' 
# display all rules # 
alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers' 
alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers' 
alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers' 
alias iptlistfw='sudo /sbin/iptables -L FORWARD -n -v --line-numbers' 
## Show hidden files ##
alias l.='ls -d .* --color=auto'
## List install packages ##
alias list='dpkg -l | grep $1'
alias lsbig='ls -gtSrh'
alias lsnew='ls -lhat'
alias lsold='ls -lhatr'
alias mkdir='mkdir -pv'
alias mnt='mount |column -t'
alias nocomment='grep -Ev '\''^(#|$)'\'''
alias php=''
alias ports='netstat -tulanp'
alias poweroff='sudo /sbin/poweroff'
alias purge='apt-get purge $1'
alias reboot='sudo /sbin/reboot'
alias remove='apt-get remove $1'
alias search='apt-cache search $1'
alias syslog='tail -f -n 1000 /var/log/syslog'
alias research='apt-cache search -f $1'
alias update='apt-get update;apt-get dist-upgrade'
alias rmlock='rm /var/lib/dpkg/lock;rm /var/cache/apt/archives/lock;rm /var/lib/apt/lists/lock'
alias unban='iptables -D INPUT -j DROP -s'
alias webattack="tail -f -n 20000 /var/log/apache2/other_vhosts_access.log | grep 'POST /administrator' | grep -v 192.168.1.125"
alias webattackcount='cat /var/log/apache2/other_vhosts_access.log | wc'
alias webtraffic='tail -f -n 2000 /var/log/apache2/other_vhosts_access.log | grep -v 192.168.1.125'
